package paneles;

import Conexion.conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import static paneles.inicio.ProgressBar;
import static paneles.inicio.pb;

public class ConfiguracionAdmin extends javax.swing.JPanel {

    private TableRowSorter<DefaultTableModel> sorter;

    public ConfiguracionAdmin() {
        initComponents();

        setBackground(new Color(0, 0, 0, 0));
        setBackground(new Color(0, 0, 0, 0));
        tUsuarios.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tUsuarios.getTableHeader().setOpaque(false);
        tUsuarios.setRowHeight(25);

        MostarDatos();
        limpiarcajas();
        bloquearNuevoUsuario();
        //bloquearEditUsuario();
        PanelUsuario.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioDeSesion4 = new javax.swing.JButton();
        HoraSemestre = new javax.swing.JPanel();
        Usuario = new javax.swing.JPanel();
        ContenedorTitulo5 = new javax.swing.JPanel();
        Titulo5 = new javax.swing.JLabel();
        PanelUsuario = new javax.swing.JTabbedPane();
        NuevoUsuario = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        ContenedorTitulo7 = new javax.swing.JPanel();
        Titulo7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        Titulo21 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JTextField();
        ContraseñaNueva = new javax.swing.JTextField();
        GuardarNuevoUsu1 = new javax.swing.JButton();
        GuardarNuevoUsu = new javax.swing.JButton();
        Titulo20 = new javax.swing.JLabel();
        VerUsuario = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        ContenedorTitulo11 = new javax.swing.JPanel();
        Titulo11 = new javax.swing.JLabel();
        EliminarUsuario = new javax.swing.JButton();
        EditarUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTable();
        EditUsurio = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        ContenedorTitulo10 = new javax.swing.JPanel();
        Titulo10 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        Titulo28 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        Titulo29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ActualizarUsuario = new javax.swing.JButton();
        contraseña = new javax.swing.JTextField();
        idEditar1 = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        Titulo27 = new javax.swing.JLabel();

        InicioDeSesion4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InicioDeSesion4.setForeground(new java.awt.Color(25, 118, 211));
        InicioDeSesion4.setText("REGISTRA EL DIA INABIL");
        InicioDeSesion4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InicioDeSesion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioDeSesion4ActionPerformed(evt);
            }
        });

        HoraSemestre.setBackground(new java.awt.Color(255, 255, 255));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTitulo5.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTitulo5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Titulo5.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo5.setText("Configuraciones Del Usuario");

        javax.swing.GroupLayout ContenedorTitulo5Layout = new javax.swing.GroupLayout(ContenedorTitulo5);
        ContenedorTitulo5.setLayout(ContenedorTitulo5Layout);
        ContenedorTitulo5Layout.setHorizontalGroup(
            ContenedorTitulo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorTitulo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTitulo5Layout.setVerticalGroup(
            ContenedorTitulo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        NuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setForeground(new java.awt.Color(51, 0, 255));

        Titulo7.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo7.setText("Nuevo Usuario ");

        javax.swing.GroupLayout ContenedorTitulo7Layout = new javax.swing.GroupLayout(ContenedorTitulo7);
        ContenedorTitulo7.setLayout(ContenedorTitulo7Layout);
        ContenedorTitulo7Layout.setHorizontalGroup(
            ContenedorTitulo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ContenedorTitulo7Layout.setVerticalGroup(
            ContenedorTitulo7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        Titulo21.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        Titulo21.setText("Contraseña:");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(Titulo21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________");

        Usuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario2ActionPerformed(evt);
            }
        });
        Usuario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Usuario2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Usuario2KeyTyped(evt);
            }
        });

        ContraseñaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaNuevaActionPerformed(evt);
            }
        });
        ContraseñaNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContraseñaNuevaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaNuevaKeyTyped(evt);
            }
        });

        GuardarNuevoUsu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuardarNuevoUsu1.setForeground(new java.awt.Color(25, 118, 211));
        GuardarNuevoUsu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-usuario.png"))); // NOI18N
        GuardarNuevoUsu1.setText("NUEVO USUARIO");
        GuardarNuevoUsu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarNuevoUsu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNuevoUsu1ActionPerformed(evt);
            }
        });

        GuardarNuevoUsu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuardarNuevoUsu.setForeground(new java.awt.Color(25, 118, 211));
        GuardarNuevoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar-datos.png"))); // NOI18N
        GuardarNuevoUsu.setText("GUARDAR USUARIO");
        GuardarNuevoUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarNuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNuevoUsuActionPerformed(evt);
            }
        });

        Titulo20.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        Titulo20.setText("Usuario");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Titulo20, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Usuario2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(ContraseñaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GuardarNuevoUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarNuevoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titulo20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarNuevoUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarNuevoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout NuevoUsuarioLayout = new javax.swing.GroupLayout(NuevoUsuario);
        NuevoUsuario.setLayout(NuevoUsuarioLayout);
        NuevoUsuarioLayout.setHorizontalGroup(
            NuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NuevoUsuarioLayout.setVerticalGroup(
            NuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        PanelUsuario.addTab("Nuevo Usuario", NuevoUsuario);

        VerUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        Titulo11.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo11.setText("Usuarios");

        javax.swing.GroupLayout ContenedorTitulo11Layout = new javax.swing.GroupLayout(ContenedorTitulo11);
        ContenedorTitulo11.setLayout(ContenedorTitulo11Layout);
        ContenedorTitulo11Layout.setHorizontalGroup(
            ContenedorTitulo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo11, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTitulo11Layout.setVerticalGroup(
            ContenedorTitulo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        EliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EliminarUsuario.setForeground(new java.awt.Color(25, 118, 211));
        EliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-usuario.png"))); // NOI18N
        EliminarUsuario.setText("ELIMINAR USUARIO");
        EliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });

        EditarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditarUsuario.setForeground(new java.awt.Color(25, 118, 211));
        EditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-usuario.png"))); // NOI18N
        EditarUsuario.setText("EDITAR USUARIO");
        EditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });

        tUsuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        tUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tUsuarios);
        if (tUsuarios.getColumnModel().getColumnCount() > 0) {
            tUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addComponent(jScrollPane2)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VerUsuarioLayout = new javax.swing.GroupLayout(VerUsuario);
        VerUsuario.setLayout(VerUsuarioLayout);
        VerUsuarioLayout.setHorizontalGroup(
            VerUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerUsuarioLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        VerUsuarioLayout.setVerticalGroup(
            VerUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelUsuario.addTab("Usuario", VerUsuario);

        EditUsurio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTitulo10.setBackground(new java.awt.Color(255, 255, 255));

        Titulo10.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo10.setText("Editar Usuario");

        javax.swing.GroupLayout ContenedorTitulo10Layout = new javax.swing.GroupLayout(ContenedorTitulo10);
        ContenedorTitulo10.setLayout(ContenedorTitulo10Layout);
        ContenedorTitulo10Layout.setHorizontalGroup(
            ContenedorTitulo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo10, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTitulo10Layout.setVerticalGroup(
            ContenedorTitulo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTitulo10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo10)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));

        Titulo28.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        Titulo28.setText("Usuario");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo28, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(Titulo28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));

        Titulo29.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        Titulo29.setText("Contraseña:");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo29)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("________________________________________________________________________________________________________________________________________________________________________________________________________________");

        ActualizarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ActualizarUsuario.setForeground(new java.awt.Color(25, 118, 211));
        ActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar_usuario.png"))); // NOI18N
        ActualizarUsuario.setText("ACTUALIZAR USUARIO");
        ActualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarUsuarioActionPerformed(evt);
            }
        });

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        idEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEditar1ActionPerformed(evt);
            }
        });
        idEditar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idEditar1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idEditar1KeyTyped(evt);
            }
        });

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        Titulo27.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        Titulo27.setText("Id");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Titulo27, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(contraseña)
                            .addComponent(idEditar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ActualizarUsuario)
                .addGap(416, 416, 416))
            .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel27Layout.createSequentialGroup()
                    .addGap(538, 538, 538)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(539, Short.MAX_VALUE)))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel27Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(ActualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel27Layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout EditUsurioLayout = new javax.swing.GroupLayout(EditUsurio);
        EditUsurio.setLayout(EditUsurioLayout);
        EditUsurioLayout.setHorizontalGroup(
            EditUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
            .addGroup(EditUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditUsurioLayout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        EditUsurioLayout.setVerticalGroup(
            EditUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(EditUsurioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EditUsurioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PanelUsuario.addTab("Editar Usuario", EditUsurio);

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUsuario)
                    .addComponent(ContenedorTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenedorTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelUsuario)
                .addContainerGap())
        );

        javax.swing.GroupLayout HoraSemestreLayout = new javax.swing.GroupLayout(HoraSemestre);
        HoraSemestre.setLayout(HoraSemestreLayout);
        HoraSemestreLayout.setHorizontalGroup(
            HoraSemestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HoraSemestreLayout.setVerticalGroup(
            HoraSemestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HoraSemestre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HoraSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarcajas() {
        Usuario2.setText(null);
        ContraseñaNueva.setText(null);

    }

    void bloquearNuevoUsuario() {;
        Usuario2.setEnabled(false);
        ContraseñaNueva.setEnabled(false);
        GuardarNuevoUsu.setEnabled(false);
        idEditar1.setEnabled(false);
    }

    void desbloquarNuevoUsuario() {
        Usuario2.setEnabled(true);
        ContraseñaNueva.setEnabled(true);
        GuardarNuevoUsu.setEnabled(true);
    }

    public void MostarDatos() {
        PreparedStatement ps = null;
        ResultSet rs = null;

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            tUsuarios.setModel(modelo);
            tUsuarios.setAutoCreateRowSorter(true);
            sorter = new TableRowSorter<>(modelo);
            tUsuarios.setRowSorter(sorter);

            String sql = ("select *from usuario");

            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Id");
            modelo.addColumn("Usuario");
            modelo.addColumn("Contraseña");

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            //System.err.println(ex.toString());
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void InicioDeSesion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioDeSesion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioDeSesion4ActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
        contraseña.transferFocus();
    }//GEN-LAST:event_contraseñaActionPerformed

    private void ActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarUsuarioActionPerformed

        // Actualizar usuario
        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement ps = null;

        try {
            // ✅ Consulta correcta: solo se actualizan nombre y clave
            ps = con.prepareStatement("UPDATE usuario SET nombre = ?,clave = ? WHERE id_usuario = ?");

            // Asignamos los valores en el orden correcto
            ps.setString(1, usuario.getText());              // Nuevo nombre
            ps.setString(2, contraseña.getText());           // Nueva contraseña
            ps.setInt(3, Integer.parseInt(idEditar1.getText())); // ID del usuario a actualizar

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente");
                limpiarcajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error: No se pudo actualizar el usuario");
                limpiarcajas();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
        }

        MostarDatos();

    }//GEN-LAST:event_ActualizarUsuarioActionPerformed

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyTyped

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyPressed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        usuario.transferFocus();
    }//GEN-LAST:event_usuarioActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        // TODO add your handling code here:
        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement ps = null;
        ResultSet rs;
        PanelUsuario.setSelectedIndex(2);

        if (tUsuarios.getSelectedRow() != -1) { // Verifica si se seleccionó alguna fila

            int fila = tUsuarios.getSelectedRow();

            idEditar1.setText(tUsuarios.getValueAt(fila, 0).toString());
            usuario.setText(tUsuarios.getValueAt(fila, 1).toString());
            contraseña.setText(tUsuarios.getValueAt(fila, 2).toString());

            try {
                int valor = 0;
                ps = con.prepareStatement("select id_usuario  from usuario where id_usuario=?");
                ResultSet res = ps.executeQuery();
                if (res.next()) {
                    valor = res.getInt("id_usuario");
                }

            } catch (Exception e) {
                System.err.println(e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun usuario ", "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement ps = null;
        ResultSet rs;

        int fila = tUsuarios.getSelectedRow();

        if (fila != -1) { // Verifica si se seleccionó alguna fila
            try {
                String valor = tUsuarios.getValueAt(fila, 0).toString();
                ps = con.prepareStatement("DELETE FROM usuario WHERE id_usuario = ? and id_usuario != 1");
                ps.setString(1, valor);
                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario se eliminó con éxito");
                    limpiarcajas();
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario principal no puede eliminarse");
                }
            } catch (Exception e) {
                //System.err.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningún usuario ", "Error", JOptionPane.ERROR_MESSAGE);
        }

        MostarDatos();

    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void GuardarNuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNuevoUsuActionPerformed
        // TODO add your handling code here:

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement ps = null;

        try {
            ps = con.prepareStatement("INSERT INTO usuario (nombre, clave) VALUES (?, ?)");

            ps.setString(1, Usuario2.getText());
            ps.setString(2, ContraseñaNueva.getText());

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Nuevo Usuario Creado");
                limpiarcajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al crear el nuevo usuario");
                limpiarcajas();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al insertar usuario: " + e.getMessage());
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
        }
        bloquearNuevoUsuario();
        MostarDatos();

    }//GEN-LAST:event_GuardarNuevoUsuActionPerformed

    private void GuardarNuevoUsu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNuevoUsu1ActionPerformed
        // TODO add your handling code here:
        desbloquarNuevoUsuario();
    }//GEN-LAST:event_GuardarNuevoUsu1ActionPerformed

    private void ContraseñaNuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaNuevaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaNuevaKeyTyped

    private void ContraseñaNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaNuevaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaNuevaKeyPressed

    private void ContraseñaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaNuevaActionPerformed
        // TODO add your handling code here:
        ContraseñaNueva.transferFocus();
    }//GEN-LAST:event_ContraseñaNuevaActionPerformed

    private void Usuario2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Usuario2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario2KeyTyped

    private void Usuario2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Usuario2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario2KeyPressed

    private void Usuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario2ActionPerformed
        // TODO add your handling code here:
        Usuario2.transferFocus();

    }//GEN-LAST:event_Usuario2ActionPerformed

    private void idEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEditar1ActionPerformed
        // TODO add your handling code here:
        idEditar1.transferFocus();
    }//GEN-LAST:event_idEditar1ActionPerformed

    private void idEditar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idEditar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEditar1KeyPressed

    private void idEditar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idEditar1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_SPACE) {
            evt.consume(); // Esto evita que el carácter ingresado se muestre en el campo de texto

            // Muestra el mensaje de alerta
            JOptionPane.showMessageDialog(null, "Ingrese solo números", "Error de caractér", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_idEditar1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarUsuario;
    private javax.swing.JPanel ContenedorTitulo10;
    private javax.swing.JPanel ContenedorTitulo11;
    private javax.swing.JPanel ContenedorTitulo5;
    private javax.swing.JPanel ContenedorTitulo7;
    private javax.swing.JTextField ContraseñaNueva;
    private javax.swing.JPanel EditUsurio;
    private javax.swing.JButton EditarUsuario;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JButton GuardarNuevoUsu;
    private javax.swing.JButton GuardarNuevoUsu1;
    private javax.swing.JPanel HoraSemestre;
    private javax.swing.JButton InicioDeSesion4;
    private javax.swing.JPanel NuevoUsuario;
    private javax.swing.JTabbedPane PanelUsuario;
    private javax.swing.JLabel Titulo10;
    private javax.swing.JLabel Titulo11;
    private javax.swing.JLabel Titulo20;
    private javax.swing.JLabel Titulo21;
    private javax.swing.JLabel Titulo27;
    private javax.swing.JLabel Titulo28;
    private javax.swing.JLabel Titulo29;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JLabel Titulo7;
    private javax.swing.JPanel Usuario;
    private javax.swing.JTextField Usuario2;
    private javax.swing.JPanel VerUsuario;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField idEditar1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tUsuarios;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

}
