package paneles;

import Conexion.conexion;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileNotFoundException;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import java.io.File;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class inicio extends javax.swing.JPanel {

    private JTable jTable;
    private DefaultTableModel dtm;
    private Object[] o = new Object[6];
    private TableRowSorter<DefaultTableModel> sorter;
    JFileChooser selecArchivo = new JFileChooser();

    public inicio() {
        initComponents();

        setBackground(new Color(0, 0, 0, 0));
        TablaCatalogo.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaCatalogo.getTableHeader().setOpaque(false);
        TablaCatalogo.setRowHeight(25);

        setBackground(new Color(0, 0, 0, 0));
        TablaProductoIva.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaProductoIva.getTableHeader().setOpaque(false);
        TablaProductoIva.setRowHeight(25);

        MostarDatosCatalogo();
        MostarMenuSemanal();
        MostarProductosIVA();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        ContenedorTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContenedorMenu = new javax.swing.JPanel();
        SubirCatalogo = new javax.swing.JButton();
        SubirProductosIVA = new javax.swing.JButton();
        SubirMenuSemanal = new javax.swing.JButton();
        ContenedorTablaAsistenciaHorario = new javax.swing.JPanel();
        TituloDeLaTabla = new javax.swing.JTabbedPane();
        ScrollTablaCatalogo = new javax.swing.JScrollPane();
        TablaCatalogo = new javax.swing.JTable();
        ScrollProductoIva = new javax.swing.JScrollPane();
        TablaProductoIva = new javax.swing.JTable();
        ScrollMenuSemanal = new javax.swing.JScrollPane();
        TablaMenu = new javax.swing.JTable();
        ProgressBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTitulo.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Titulo.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Inicio");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ContenedorTituloLayout = new javax.swing.GroupLayout(ContenedorTitulo);
        ContenedorTitulo.setLayout(ContenedorTituloLayout);
        ContenedorTituloLayout.setHorizontalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTituloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTituloLayout.setVerticalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContenedorMenu.setBackground(new java.awt.Color(255, 255, 255));

        SubirCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo.png"))); // NOI18N
        SubirCatalogo.setText("Subir Catalogo");
        SubirCatalogo.setFocusPainted(false);
        SubirCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirCatalogoActionPerformed(evt);
            }
        });

        SubirProductosIVA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icondia.png"))); // NOI18N
        SubirProductosIVA.setText("Subir Productos IVA");
        SubirProductosIVA.setFocusPainted(false);
        SubirProductosIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirProductosIVAActionPerformed(evt);
            }
        });

        SubirMenuSemanal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icondia.png"))); // NOI18N
        SubirMenuSemanal.setText("Subir Menu Semanal");
        SubirMenuSemanal.setFocusPainted(false);
        SubirMenuSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirMenuSemanalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorMenuLayout = new javax.swing.GroupLayout(ContenedorMenu);
        ContenedorMenu.setLayout(ContenedorMenuLayout);
        ContenedorMenuLayout.setHorizontalGroup(
            ContenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubirCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubirProductosIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubirMenuSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        ContenedorMenuLayout.setVerticalGroup(
            ContenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubirCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubirProductosIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubirMenuSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ContenedorTablaAsistenciaHorario.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTablaAsistenciaHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TituloDeLaTabla.setBackground(new java.awt.Color(255, 255, 255));

        TablaCatalogo = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        TablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_producto", "Partida", "Rubro", "Unidad De Medida", "Descripcion", "Marca", "Cantidad", "Precio", "Observacion"
            }
        ));
        TablaCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCatalogoMouseClicked(evt);
            }
        });
        ScrollTablaCatalogo.setViewportView(TablaCatalogo);

        TituloDeLaTabla.addTab("Catalogo", ScrollTablaCatalogo);

        TablaProductoIva = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        TablaProductoIva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_producto", "Rubro", "Descripcion Articulo", "Marca", "Cantidad"
            }
        ));
        ScrollProductoIva.setViewportView(TablaProductoIva);

        TituloDeLaTabla.addTab("Productos IVA", ScrollProductoIva);

        TablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo Comida", "Lunes ", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ));
        ScrollMenuSemanal.setViewportView(TablaMenu);

        TituloDeLaTabla.addTab("Menu Semanal", ScrollMenuSemanal);

        ProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        ProgressBar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ProgressBar.setForeground(new java.awt.Color(51, 153, 255));
        ProgressBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProgressBar.setRequestFocusEnabled(false);
        ProgressBar.setStringPainted(true);

        javax.swing.GroupLayout ContenedorTablaAsistenciaHorarioLayout = new javax.swing.GroupLayout(ContenedorTablaAsistenciaHorario);
        ContenedorTablaAsistenciaHorario.setLayout(ContenedorTablaAsistenciaHorarioLayout);
        ContenedorTablaAsistenciaHorarioLayout.setHorizontalGroup(
            ContenedorTablaAsistenciaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTablaAsistenciaHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorTablaAsistenciaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TituloDeLaTabla, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ContenedorTablaAsistenciaHorarioLayout.setVerticalGroup(
            ContenedorTablaAsistenciaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorTablaAsistenciaHorarioLayout.createSequentialGroup()
                .addComponent(TituloDeLaTabla)
                .addGap(12, 12, 12)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenedorTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenedorTablaAsistenciaHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ContenedorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContenedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContenedorTablaAsistenciaHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //progress bar subir excel
    public static void pb() {
        Thread hilos = new Thread() {
            public void run() {

                for (int a = 0; a <= 100; a++) {
                    try {
                        ProgressBar.setValue(a);
                        Thread.sleep(4);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        };
        hilos.start();
    }

    //SUBIR EL CATALOGO A LA BASE DE DATOS 
    private void SubirCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirCatalogoActionPerformed

        SubirBdCatalogo();
        MostarDatosCatalogo();
    }//GEN-LAST:event_SubirCatalogoActionPerformed

    //Registra los productos del catalogo de excel a la base de datos
    public static void SubirALaBaseCatalogo() throws IOException, SQLException {

        conexion conn = new conexion();
        Connection con = null;
        PreparedStatement ps = null;

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try (FileInputStream file = new FileInputStream(selectedFile); XSSFWorkbook workbook = new XSSFWorkbook(file)) {

                org.apache.poi.ss.usermodel.Sheet sheet = workbook.getSheetAt(0);
                con = conn.Conectar();

                String sql = "INSERT INTO CATALOGO (partida, rubro, unidad_medida, descripcion, marca, cantidad, precio, observacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                ps = con.prepareStatement(sql);

                int numFilas = sheet.getLastRowNum();
                int registrosInsertados = 0;

                for (int i = 1; i <= numFilas; i++) { // Empieza desde fila 2
                    Row fila = sheet.getRow(i);
                    if (fila == null) //si la fila esta vacia, saltar 
                    {
                        continue;
                    }
                    
                    ps.setString(1, obtenerValorCelda(fila, 0));
                    ps.setString(2, obtenerValorCelda(fila, 1));
                    ps.setString(3, obtenerValorCelda(fila, 2));
                    ps.setString(4, obtenerValorCelda(fila, 3));
                    ps.setString(5, obtenerValorCelda(fila, 4));
                    ps.setString(6, obtenerValorCelda(fila, 5));
                    ps.setString(7, obtenerValorCelda(fila, 6));
                    ps.setString(8, obtenerValorCelda(fila, 7));

                    ps.addBatch(); // Agrega al batch
                    registrosInsertados++;

                    // Ejecuta cada 500 filas para optimizar rendimiento
                    if (registrosInsertados % 500 == 0) {
                        ps.executeBatch();
                    }
                }

                // Ejecutar el resto
                ps.executeBatch();

                JOptionPane.showMessageDialog(null, "Archivo subido con éxito. Registros insertados: " + registrosInsertados,
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Archivo no encontrado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }

    }

    private static String obtenerValorCelda(Row fila, int indice) {
        Cell celda = fila.getCell(indice);
        if (celda == null) {
            return "";
        }

        switch (celda.getCellType()) {
            case STRING:
                return celda.getStringCellValue().trim();
            case NUMERIC:
                if (DateUtil.isCellDateFormatted(celda)) {
                    return celda.getDateCellValue().toString();
                } else {
                    double val = celda.getNumericCellValue();
                    if (val == Math.floor(val)) {
                        return String.valueOf((long) val);
                    } else {
                        return String.valueOf(val);
                    }
                }
            case BOOLEAN:
                return String.valueOf(celda.getBooleanCellValue());
            case FORMULA:
                try {
                    return celda.getStringCellValue();
                } catch (IllegalStateException e) {
                    return String.valueOf(celda.getNumericCellValue());
                }
            default:
                return "";
        }
    }

    //Mostramos el el catalogo de productos de catalogo
    public void MostarDatosCatalogo() {
        PreparedStatement ps = null;
        ResultSet rs = null;

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        try {

            DefaultTableModel modelo = new DefaultTableModel();
            TablaCatalogo.setModel(modelo);
            TablaCatalogo.setAutoCreateRowSorter(true);

            sorter = new TableRowSorter<>(modelo);
            TablaCatalogo.setRowSorter(sorter);

            String sql = ("select *from catalogo");

            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Partida");
            modelo.addColumn("Rubro");
            modelo.addColumn("Unidad medida");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Marca");
            modelo.addColumn("Cantidad ");
            modelo.addColumn("Precio");
            modelo.addColumn("Observacion");

            /* centrar datos */
            DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) TablaCatalogo.getTableHeader().getDefaultRenderer();
            headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            headerRenderer.setFont(headerRenderer.getFont().deriveFont(Font.BOLD)); // Establecer la fuente en negritas

            TablaCatalogo.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(1).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(2).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(3).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(4).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(5).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(6).setHeaderRenderer(headerRenderer);
            TablaCatalogo.getColumnModel().getColumn(7).setHeaderRenderer(headerRenderer);

            DefaultTableCellRenderer ColumCenter = new DefaultTableCellRenderer();
            ColumCenter.setHorizontalAlignment(SwingConstants.CENTER);
            TablaCatalogo.getColumnModel().getColumn(0).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(1).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(2).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(3).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(4).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(5).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(6).setCellRenderer(ColumCenter);
            TablaCatalogo.getColumnModel().getColumn(7).setCellRenderer(ColumCenter);

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void SubirBdCatalogo() {

        try {
            SubirALaBaseCatalogo();
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /// subir a base de datos los producto con iva
    
    
    public static void SubirALaBaseProductoIva() throws IOException, SQLException {

       conexion conn = new conexion();
        Connection con = null;
        PreparedStatement ps = null;

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try (FileInputStream file = new FileInputStream(selectedFile); XSSFWorkbook workbook = new XSSFWorkbook(file)) {

                org.apache.poi.ss.usermodel.Sheet sheet = workbook.getSheetAt(0);
                con = conn.Conectar();

                String sql = "INSERT INTO PRODUCTo_IVA (id, rubro, unidad, articulo, marca, cantidad ) VALUES (?, ?, ?, ?, ?, ?)";

                ps = con.prepareStatement(sql);

                int numFilas = sheet.getLastRowNum();
                int registrosInsertados = 0;

                for (int i = 1; i <= numFilas; i++) { // Empieza desde fila 2
                    Row fila = sheet.getRow(i);
                    if (fila == null) //si la fila esta vacia, saltar 
                    {
                        continue;
                    }
                    
                    ps.setString(1, obtenerValorCelda(fila, 0));
                    ps.setString(2, obtenerValorCelda(fila, 1));
                    ps.setString(3, obtenerValorCelda(fila, 2));
                    ps.setString(4, obtenerValorCelda(fila, 3));
                    ps.setString(5, obtenerValorCelda(fila, 4));
                    ps.setString(6, obtenerValorCelda(fila, 5));

                    ps.addBatch(); // Agrega al batch
                    registrosInsertados++;

                    // Ejecuta cada 500 filas para optimizar rendimiento
                    if (registrosInsertados % 500 == 0) {
                        ps.executeBatch();
                    }
                }

                // Ejecutar el resto
                ps.executeBatch();

                JOptionPane.showMessageDialog(null, "Archivo subido con éxito. Registros insertados: " + registrosInsertados,
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Archivo no encontrado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }

    }

    public void MostarProductosIVA() {
       PreparedStatement ps = null;
        ResultSet rs = null;

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        try {

            DefaultTableModel modelo = new DefaultTableModel();
            TablaProductoIva.setModel(modelo);
            TablaProductoIva.setAutoCreateRowSorter(true);

            sorter = new TableRowSorter<>(modelo);
            TablaProductoIva.setRowSorter(sorter);

            String sql = ("select rubro, unidad, articulo, marca, cantidad from PRODUCTo_IVA");

            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Rubro");
            modelo.addColumn("Unidad");
            modelo.addColumn("Articulo");
            modelo.addColumn("Marca");
            modelo.addColumn("Cantidad");


            /* centrar datos */
            DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) TablaProductoIva.getTableHeader().getDefaultRenderer();
            headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            headerRenderer.setFont(headerRenderer.getFont().deriveFont(Font.BOLD)); // Establecer la fuente en negritas

            TablaProductoIva.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
            TablaProductoIva.getColumnModel().getColumn(1).setHeaderRenderer(headerRenderer);
            TablaProductoIva.getColumnModel().getColumn(2).setHeaderRenderer(headerRenderer);
            TablaProductoIva.getColumnModel().getColumn(3).setHeaderRenderer(headerRenderer);
            TablaProductoIva.getColumnModel().getColumn(4).setHeaderRenderer(headerRenderer);
            
            DefaultTableCellRenderer ColumCenter = new DefaultTableCellRenderer();
            ColumCenter.setHorizontalAlignment(SwingConstants.CENTER);
            TablaProductoIva.getColumnModel().getColumn(0).setCellRenderer(ColumCenter);
            TablaProductoIva.getColumnModel().getColumn(1).setCellRenderer(ColumCenter);
            TablaProductoIva.getColumnModel().getColumn(2).setCellRenderer(ColumCenter);
            TablaProductoIva.getColumnModel().getColumn(3).setCellRenderer(ColumCenter);
            TablaProductoIva.getColumnModel().getColumn(4).setCellRenderer(ColumCenter);

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    
    /// subir a base de datos el menu_semanal  
    private void SubirMenuSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirMenuSemanalActionPerformed
        try {
            // TODO add your handling code here:
            SubirALaBaseMenusemanal();
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
            MostarMenuSemanal();
    }//GEN-LAST:event_SubirMenuSemanalActionPerformed

    public static void SubirALaBaseMenusemanal() throws IOException, SQLException {

        conexion conn = new conexion();
        Connection con = null;
        PreparedStatement ps = null;

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try (FileInputStream file = new FileInputStream(selectedFile); XSSFWorkbook workbook = new XSSFWorkbook(file)) {

                org.apache.poi.ss.usermodel.Sheet sheet = workbook.getSheetAt(0);
                con = conn.Conectar();

                String sql = "INSERT INTO MENU_SEMANAL (id_menu, tipo_comida, lunes, martes, miercoles, jueves, viernes ) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?)";
                ps = con.prepareStatement(sql);

                int numFilas = sheet.getLastRowNum();
                int registrosInsertados = 0;

                for (int i = 1; i <= numFilas; i++) { // Empieza desde fila 6 como en tu código original
                    Row fila = sheet.getRow(i);
                    if (fila == null) {
                        continue;
                    }
                    
                    ps.setString(1, obtenerValorCelda(fila, 0));
                    ps.setString(2, obtenerValorCelda(fila, 1));
                    ps.setString(3, obtenerValorCelda(fila, 2));
                    ps.setString(4, obtenerValorCelda(fila, 3));
                    ps.setString(5, obtenerValorCelda(fila, 4));
                    ps.setString(6, obtenerValorCelda(fila, 5));
                    ps.setString(7, obtenerValorCelda(fila, 6));
                    
                    ps.addBatch(); // Agrega al batch
                    registrosInsertados++;

                    // Ejecuta cada 500 filas para optimizar rendimiento
                    if (registrosInsertados % 500 == 0) {
                        ps.executeBatch();
                    }
                }

                // Ejecutar el resto
                ps.executeBatch();

                JOptionPane.showMessageDialog(null, "Archivo subido con éxito. Registros insertados: " + registrosInsertados,
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Archivo no encontrado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
                }
            }
        }
    }

    public void MostarMenuSemanal() {
        PreparedStatement ps = null;
        ResultSet rs = null;

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        try {

            DefaultTableModel modelo = new DefaultTableModel();
            TablaMenu.setModel(modelo);
            TablaMenu.setAutoCreateRowSorter(true);

            sorter = new TableRowSorter<>(modelo);
            TablaMenu.setRowSorter(sorter);

            String sql = ("SELECT tipo_comida, lunes , martes, miercoles, jueves, viernes FROM MENU_SEMANAL");

            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Tipo de comida ");
            modelo.addColumn("Lunes");
            modelo.addColumn("Martes");
            modelo.addColumn("Miercoles");
            modelo.addColumn("Jueves");
            modelo.addColumn("Viernes");


           
            DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) TablaMenu.getTableHeader().getDefaultRenderer();
            headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            headerRenderer.setFont(headerRenderer.getFont().deriveFont(Font.BOLD)); // Establecer la fuente en negritas

            TablaMenu.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
            TablaMenu.getColumnModel().getColumn(2).setHeaderRenderer(headerRenderer);
            TablaMenu.getColumnModel().getColumn(3).setHeaderRenderer(headerRenderer);
            TablaMenu.getColumnModel().getColumn(4).setHeaderRenderer(headerRenderer);
            TablaMenu.getColumnModel().getColumn(5).setHeaderRenderer(headerRenderer);

            DefaultTableCellRenderer ColumCenter = new DefaultTableCellRenderer();
            ColumCenter.setHorizontalAlignment(SwingConstants.CENTER);
            
            TablaMenu.getColumnModel().getColumn(0).setCellRenderer(ColumCenter);
            TablaMenu.getColumnModel().getColumn(1).setCellRenderer(ColumCenter);
            TablaMenu.getColumnModel().getColumn(2).setCellRenderer(ColumCenter);
            TablaMenu.getColumnModel().getColumn(3).setCellRenderer(ColumCenter);
            TablaMenu.getColumnModel().getColumn(4).setCellRenderer(ColumCenter);
            TablaMenu.getColumnModel().getColumn(5).setCellRenderer(ColumCenter);

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void TablaCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCatalogoMouseClicked

    }//GEN-LAST:event_TablaCatalogoMouseClicked

    
    private void SubirProductosIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirProductosIVAActionPerformed
        try {
            SubirALaBaseProductoIva();
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        MostarProductosIVA();
    }//GEN-LAST:event_SubirProductosIVAActionPerformed

    /*
    public void  SubirBDmenu() {

        try {
            SubirALaBaseMenusemanal();
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorMenu;
    private javax.swing.JPanel ContenedorTablaAsistenciaHorario;
    private javax.swing.JPanel ContenedorTitulo;
    public static javax.swing.JProgressBar ProgressBar;
    private javax.swing.JScrollPane ScrollMenuSemanal;
    private javax.swing.JScrollPane ScrollProductoIva;
    private javax.swing.JScrollPane ScrollTablaCatalogo;
    public javax.swing.JButton SubirCatalogo;
    private javax.swing.JButton SubirMenuSemanal;
    private javax.swing.JButton SubirProductosIVA;
    private javax.swing.JTable TablaCatalogo;
    private javax.swing.JTable TablaMenu;
    private javax.swing.JTable TablaProductoIva;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTabbedPane TituloDeLaTabla;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
