package paneles;

import Conexion.conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class MenuSemanal extends javax.swing.JPanel {

    /**
     * Creates new form recordatorio
     */
    private TableRowSorter<DefaultTableModel> sorter;

    private String archivo;

    Calendar fechaactual = new GregorianCalendar();
    Calendar fechaactuall = new GregorianCalendar();

    public MenuSemanal() {
        initComponents();
    
        setBackground(new Color(0, 0, 0, 0));
        TablaEmpleados.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaEmpleados.getTableHeader().setOpaque(false);
        TablaEmpleados.setRowHeight(25);
         
        fechainicio.setCalendar(fechaactual);
        fechafinal.setCalendar(fechaactual);

        Data("", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        ContenedorTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContenedorPanel = new javax.swing.JPanel();
        NombrePlatillo = new javax.swing.JLabel();
        ContenedorNombre = new javax.swing.JTextField();
        FechaInicio = new javax.swing.JLabel();
        fechainicio = new com.toedter.calendar.JDateChooser();
        FechaFinal = new javax.swing.JLabel();
        fechafinal = new com.toedter.calendar.JDateChooser();
        BuscarRecordatorio = new javax.swing.JButton();
        TituloDeLaTabla = new javax.swing.JTabbedPane();
        ContenedorDeLaTablaEmpleados = new javax.swing.JPanel();
        ScrollTablaEmpleados = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTitulo.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Titulo.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Menu semanal");

        javax.swing.GroupLayout ContenedorTituloLayout = new javax.swing.GroupLayout(ContenedorTitulo);
        ContenedorTitulo.setLayout(ContenedorTituloLayout);
        ContenedorTituloLayout.setHorizontalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTituloLayout.setVerticalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ContenedorPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        NombrePlatillo.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        NombrePlatillo.setText("Nombre del paltillo:");

        ContenedorNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContenedorNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContenedorNombreMouseClicked(evt);
            }
        });
        ContenedorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenedorNombreActionPerformed(evt);
            }
        });
        ContenedorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContenedorNombreKeyTyped(evt);
            }
        });

        FechaInicio.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        FechaInicio.setText("Fecha de Inicio");

        fechainicio.setDateFormatString("d/MM/yyy");

        FechaFinal.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        FechaFinal.setText("Fecha Final");

        fechafinal.setDateFormatString("d/MM/yyy");

        BuscarRecordatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        BuscarRecordatorio.setText("Buscar");
        BuscarRecordatorio.setFocusPainted(false);
        BuscarRecordatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRecordatorioActionPerformed(evt);
            }
        });

        ContenedorDeLaTablaEmpleados.setBackground(new java.awt.Color(255, 255, 255));

        TablaEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipod de comida", "Lunes", "Martes", "Miercoles", "Jueves ", "Viernes "
            }
        ));
        ScrollTablaEmpleados.setViewportView(TablaEmpleados);

        javax.swing.GroupLayout ContenedorDeLaTablaEmpleadosLayout = new javax.swing.GroupLayout(ContenedorDeLaTablaEmpleados);
        ContenedorDeLaTablaEmpleados.setLayout(ContenedorDeLaTablaEmpleadosLayout);
        ContenedorDeLaTablaEmpleadosLayout.setHorizontalGroup(
            ContenedorDeLaTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 1625, Short.MAX_VALUE)
        );
        ContenedorDeLaTablaEmpleadosLayout.setVerticalGroup(
            ContenedorDeLaTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        TituloDeLaTabla.addTab("Menu Semanal", ContenedorDeLaTablaEmpleados);

        javax.swing.GroupLayout ContenedorPanelLayout = new javax.swing.GroupLayout(ContenedorPanel);
        ContenedorPanel.setLayout(ContenedorPanelLayout);
        ContenedorPanelLayout.setHorizontalGroup(
            ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombrePlatillo)
                .addGap(18, 18, 18)
                .addComponent(ContenedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaInicio))
                .addGap(18, 18, 18)
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorPanelLayout.createSequentialGroup()
                        .addComponent(fechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(BuscarRecordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FechaFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(491, Short.MAX_VALUE))
            .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenedorPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TituloDeLaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ContenedorPanelLayout.setVerticalGroup(
            ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaInicio))
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombrePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContenedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenedorPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarRecordatorio))))
                .addContainerGap(545, Short.MAX_VALUE))
            .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenedorPanelLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(TituloDeLaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenedorTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ContenedorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarRecordatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRecordatorioActionPerformed
        // TODO add your handling code here:
        try {

            TablaEmpleados.setModel(new DefaultTableModel(null, new Object[]{"Ciclo_escolar", "Dia pendiente"}));

            SimpleDateFormat df = new SimpleDateFormat("d/MM/yyy");
            String date1 = df.format(fechainicio.getDate());
            String date2 = df.format(fechafinal.getDate());

            Data(date1, date2);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_BuscarRecordatorioActionPerformed

    private void ContenedorNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorNombreMouseClicked
        if (evt.getClickCount() == 2) {
            ContenedorNombre.setText("");

        }
    }//GEN-LAST:event_ContenedorNombreMouseClicked

    private void ContenedorNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContenedorNombreKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_SPACE) {
            evt.consume(); // Esto evita que el carácter ingresado se muestre en el campo de texto

            // Muestra el mensaje de alerta
            JOptionPane.showMessageDialog(null, "Ingrese solo texto", "Error de caractér", JOptionPane.ERROR_MESSAGE);
        }

        String palabra = ContenedorNombre.getText();
        if (palabra.length() > 0) {
            char primeraletra = palabra.charAt(0);
            palabra = Character.toUpperCase(primeraletra) + palabra.substring(1, palabra.length());
            ContenedorNombre.setText(palabra);
        }
    }//GEN-LAST:event_ContenedorNombreKeyTyped

    private void ContenedorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenedorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenedorNombreActionPerformed

    //una tabla que muestra los días que no han sido registrados en la base de datos de acuerdo al ciclo escolar con el que se esta trabajando 
    public void Data(String d1, String d2) {
        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement st = null;
        ResultSet rs = null;

        try {

            if (d1.equals("") || d2.equals("")) {
                st = con.prepareStatement("select substring(Semestre,1,12) as Ciclo_escolar, concat(substring(dia_pendiente,1,2),'/',substring(dia_pendiente,4,2),'/20',substring(dia_pendiente,7,2)) as dia_pendiente from dias_pendientes\n"
                        + "                        left join incidencias_semestre on concat(substring(dia_pendiente,1,2),'/',substring(dia_pendiente,4,2),'/20',substring(dia_pendiente,7,2)) = date_format(Fecha,'%d/%m/%Y')\n"
                        + "                        where fecha is null  and Dia_Pendiente NOT IN (\n"
                        + "                            SELECT CONCAT(SUBSTRING(fecha_inhabil, 1, 6), SUBSTRING(fecha_inhabil, 9, 10)) AS fecha\n"
                        + "                           FROM dias_inhabiles\n"
                        + "                        )\n"
                        + "                        group by Ciclo_escolar,Dia_Pendiente,semestre;");
                TablaEmpleados.setModel(new DefaultTableModel(null, new Object[]{"Ciclo Escolar", "Dia Pendiente",}));
                SimpleDateFormat df = new SimpleDateFormat("d/MM/yyy");
                String date1 = df.format(fechainicio.getDate());
                String date2 = df.format(fechafinal.getDate());
                Data(date1, date2);

            } else {
                st = con.prepareStatement("select substring(Semestre,1,12) as Ciclo_escolar, concat(substring(dia_pendiente,1,2),'/',substring(dia_pendiente,4,2),'/20',substring(dia_pendiente,7,2)) as dia_pendiente from dias_pendientes\n"
                        + "left join incidencias_semestre on concat(substring(dia_pendiente,1,2),'/',substring(dia_pendiente,4,2),'/20',substring(dia_pendiente,7,2)) = date_format(Fecha,'%d/%m/%Y')\n"
                        + "where fecha is null and str_to_date(concat(substring(dia_pendiente,1,2),'/',substring(dia_pendiente,4,2),'/20',substring(dia_pendiente,7,2)),'%d/%m/%Y') between str_to_date(?,'%d/%m/%Y') and str_to_date(?,'%d/%m/%Y')  and Dia_Pendiente NOT IN (\n"
                        + "    SELECT CONCAT(SUBSTRING(fecha_inhabil, 1, 6), SUBSTRING(fecha_inhabil, 9, 10)) AS fecha\n"
                        + "    FROM dias_inhabiles\n"
                        + ")\n"
                        + "group by Ciclo_escolar,Dia_Pendiente,semestre;");

                st.setString(1, d1);
                st.setString(2, d2);
            }

            rs = st.executeQuery();
            DefaultTableModel model = (DefaultTableModel) TablaEmpleados.getModel();

            Object[] row;

            while (rs.next()) {
                row = new Object[2];
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);

                model.addRow(row);
            }

        } catch (Exception e) {

            //System.out.println(e.getMessage());
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarRecordatorio;
    private javax.swing.JPanel ContenedorDeLaTablaEmpleados;
    private javax.swing.JTextField ContenedorNombre;
    private javax.swing.JPanel ContenedorPanel;
    private javax.swing.JPanel ContenedorTitulo;
    private javax.swing.JLabel FechaFinal;
    private javax.swing.JLabel FechaInicio;
    private javax.swing.JLabel NombrePlatillo;
    private javax.swing.JScrollPane ScrollTablaEmpleados;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTabbedPane TituloDeLaTabla;
    private com.toedter.calendar.JDateChooser fechafinal;
    private com.toedter.calendar.JDateChooser fechainicio;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
