package paneles;

import Conexion.conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class MenuSemanal extends javax.swing.JPanel {

    /**
     * Creates new form recordatorio
     */
    private TableRowSorter<DefaultTableModel> sorter;

    private String archivo;

    Calendar fechaactual = new GregorianCalendar();
    Calendar fechaactuall = new GregorianCalendar();

    public MenuSemanal() {
        initComponents();

        setBackground(new Color(0, 0, 0, 0));
        TablaMenuSemanal.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        TablaMenuSemanal.getTableHeader().setOpaque(false);
        TablaMenuSemanal.setRowHeight(25);

        fechainicio.setCalendar(fechaactual);
        fechafinal.setCalendar(fechaactual);

        MostrarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        ContenedorTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ContenedorPanel = new javax.swing.JPanel();
        NombrePlatillo = new javax.swing.JLabel();
        Nplatillo = new javax.swing.JTextField();
        FechaInicio = new javax.swing.JLabel();
        fechainicio = new com.toedter.calendar.JDateChooser();
        FechaFinal = new javax.swing.JLabel();
        fechafinal = new com.toedter.calendar.JDateChooser();
        Buscar = new javax.swing.JButton();
        TituloDeLaTabla = new javax.swing.JTabbedPane();
        ContenedorDeLaTablaEmpleados = new javax.swing.JPanel();
        ScrollTablaEmpleados = new javax.swing.JScrollPane();
        TablaMenuSemanal = new javax.swing.JTable();

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTitulo.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Titulo.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Menu semanal");

        javax.swing.GroupLayout ContenedorTituloLayout = new javax.swing.GroupLayout(ContenedorTitulo);
        ContenedorTitulo.setLayout(ContenedorTituloLayout);
        ContenedorTituloLayout.setHorizontalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorTituloLayout.setVerticalGroup(
            ContenedorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ContenedorPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        NombrePlatillo.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        NombrePlatillo.setText("Nombre del platillo:");

        Nplatillo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nplatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NplatilloMouseClicked(evt);
            }
        });
        Nplatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NplatilloActionPerformed(evt);
            }
        });
        Nplatillo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NplatilloKeyTyped(evt);
            }
        });

        FechaInicio.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        FechaInicio.setText("Fecha de Inicio");

        fechainicio.setDateFormatString("d/MM/yyy");

        FechaFinal.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        FechaFinal.setText("Fecha Final");

        fechafinal.setDateFormatString("d/MM/yyy");

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.setFocusPainted(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        ContenedorDeLaTablaEmpleados.setBackground(new java.awt.Color(255, 255, 255));

        TablaMenuSemanal = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        TablaMenuSemanal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipod de comida", "Lunes", "Martes", "Miercoles", "Jueves ", "Viernes "
            }
        ));
        ScrollTablaEmpleados.setViewportView(TablaMenuSemanal);

        javax.swing.GroupLayout ContenedorDeLaTablaEmpleadosLayout = new javax.swing.GroupLayout(ContenedorDeLaTablaEmpleados);
        ContenedorDeLaTablaEmpleados.setLayout(ContenedorDeLaTablaEmpleadosLayout);
        ContenedorDeLaTablaEmpleadosLayout.setHorizontalGroup(
            ContenedorDeLaTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 1625, Short.MAX_VALUE)
        );
        ContenedorDeLaTablaEmpleadosLayout.setVerticalGroup(
            ContenedorDeLaTablaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollTablaEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        TituloDeLaTabla.addTab("Menu Semanal", ContenedorDeLaTablaEmpleados);

        javax.swing.GroupLayout ContenedorPanelLayout = new javax.swing.GroupLayout(ContenedorPanel);
        ContenedorPanel.setLayout(ContenedorPanelLayout);
        ContenedorPanelLayout.setHorizontalGroup(
            ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombrePlatillo)
                .addGap(18, 18, 18)
                .addComponent(Nplatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorPanelLayout.createSequentialGroup()
                        .addComponent(fechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(FechaInicio)
                        .addGap(57, 57, 57)
                        .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenedorPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TituloDeLaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ContenedorPanelLayout.setVerticalGroup(
            ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar)
                    .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nplatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombrePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(ContenedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenedorPanelLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(TituloDeLaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenedorTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ContenedorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String texto = Nplatillo.getText().trim(); // Captura el texto del JTextField

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un texto para buscar.");
            return;
        }

        // Conexión a la base de datos
        conexion conn = new conexion();
        Connection con = conn.Conectar();
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            // Consulta SQL: busca en todas las columnas

            String sql = "SELECT tipo_comida, lunes, martes, miercoles, jueves, viernes "
                    + "FROM MENU_SEMANAL "
                    + "WHERE tipo_comida LIKE ? "
                    + "OR lunes LIKE ? "
                    + "OR martes LIKE ? "
                    + "OR miercoles LIKE ? "
                    + "OR jueves LIKE ? "
                    + "OR viernes LIKE ?";

            ps = con.prepareStatement(sql);
            for (int i = 1; i <= 6; i++) {
                ps.setString(i, "%" + texto + "%");
            }

            rs = ps.executeQuery();

            // Modelo para la tabla
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Tipo de comida");
            modelo.addColumn("Lunes");
            modelo.addColumn("Martes");
            modelo.addColumn("Miercoles");
            modelo.addColumn("Jueves");
            modelo.addColumn("Viernes");

            // Llenar la tabla con los resultados
            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getString("Tipo_Comida");
                fila[1] = rs.getString("Lunes");
                fila[2] = rs.getString("Martes");
                fila[3] = rs.getString("Miercoles");
                fila[4] = rs.getString("Jueves");
                fila[5] = rs.getString("Viernes");
                modelo.addRow(fila);
            }

            // Asignar el modelo a la JTable
            TablaMenuSemanal.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                System.out.println("Error al cerrar conexión: " + ex);
            }
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void NplatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NplatilloMouseClicked
        if (evt.getClickCount() == 2) {
            Nplatillo.setText("");

        }
    }//GEN-LAST:event_NplatilloMouseClicked

    private void NplatilloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NplatilloKeyTyped

    }//GEN-LAST:event_NplatilloKeyTyped

    private void NplatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NplatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NplatilloActionPerformed

    public void MostrarMenu() {
        PreparedStatement ps = null;
        ResultSet rs = null;

        conexion conn = new conexion();
        Connection con = conn.Conectar();
        try {

            DefaultTableModel modelo = new DefaultTableModel();
            TablaMenuSemanal.setModel(modelo);
            TablaMenuSemanal.setAutoCreateRowSorter(true);

            sorter = new TableRowSorter<>(modelo);
            TablaMenuSemanal.setRowSorter(sorter);

            String sql = ("SELECT tipo_comida, lunes , martes, miercoles, jueves, viernes FROM MENU_SEMANAL");

            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Tipo de comida ");
            modelo.addColumn("Lunes");
            modelo.addColumn("Martes");
            modelo.addColumn("Miercoles");
            modelo.addColumn("Jueves");
            modelo.addColumn("Viernes");


            /* centrar datos */
            DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) TablaMenuSemanal.getTableHeader().getDefaultRenderer();
            headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            headerRenderer.setFont(headerRenderer.getFont().deriveFont(Font.BOLD)); // Establecer la fuente en negritas

            TablaMenuSemanal.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
            TablaMenuSemanal.getColumnModel().getColumn(1).setHeaderRenderer(headerRenderer);
            TablaMenuSemanal.getColumnModel().getColumn(2).setHeaderRenderer(headerRenderer);
            TablaMenuSemanal.getColumnModel().getColumn(3).setHeaderRenderer(headerRenderer);
            TablaMenuSemanal.getColumnModel().getColumn(4).setHeaderRenderer(headerRenderer);
            TablaMenuSemanal.getColumnModel().getColumn(5).setHeaderRenderer(headerRenderer);

            DefaultTableCellRenderer ColumCenter = new DefaultTableCellRenderer();
            ColumCenter.setHorizontalAlignment(SwingConstants.CENTER);
            TablaMenuSemanal.getColumnModel().getColumn(0).setCellRenderer(ColumCenter);
            TablaMenuSemanal.getColumnModel().getColumn(1).setCellRenderer(ColumCenter);
            TablaMenuSemanal.getColumnModel().getColumn(2).setCellRenderer(ColumCenter);
            TablaMenuSemanal.getColumnModel().getColumn(3).setCellRenderer(ColumCenter);
            TablaMenuSemanal.getColumnModel().getColumn(4).setCellRenderer(ColumCenter);
            TablaMenuSemanal.getColumnModel().getColumn(5).setCellRenderer(ColumCenter);

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Cerrar ResultSet, PreparedStatement y Connection en el orden adecuado
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    //una tabla que muestra los días que no han sido registrados en la base de datos de acuerdo al ciclo escolar con el que se esta trabajando 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JPanel ContenedorDeLaTablaEmpleados;
    private javax.swing.JPanel ContenedorPanel;
    private javax.swing.JPanel ContenedorTitulo;
    private javax.swing.JLabel FechaFinal;
    private javax.swing.JLabel FechaInicio;
    private javax.swing.JLabel NombrePlatillo;
    private javax.swing.JTextField Nplatillo;
    private javax.swing.JScrollPane ScrollTablaEmpleados;
    private javax.swing.JTable TablaMenuSemanal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTabbedPane TituloDeLaTabla;
    private com.toedter.calendar.JDateChooser fechafinal;
    private com.toedter.calendar.JDateChooser fechainicio;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

}
